[BAC-401] Allow testing of pods created during the initial phase of a Rollout (#37)

diff --git a/src/commands/argo-migration-current-phase.yml b/src/commands/argo-migration-current-phase.yml
--- a/src/commands/argo-migration-current-phase.yml
+++ b/src/commands/argo-migration-current-phase.yml
@@ -1,6 +1,6 @@
 description: |
-  Compute the next migration phase.
-  The migration phase is written to << parameters.output-file-name >> for use in subsequent steps.
+  Compute the current migration phase.
+  The migration phase is written to << parameters.profile-file-name >> for use in subsequent steps.
 
 parameters:
   release-name:
@@ -20,9 +20,6 @@ parameters:
   profile-file-name:
     description: The name of the resulting file where attributes related to the environment will be stored
     type: string
-  output-file-name:
-    description: The name of the resulting file where the migration phase will be stored
-    type: string
 
 steps:
   - run:
@@ -37,7 +34,7 @@ steps:
         echo "📄 Environment already set up for this step"
         echo "------------------------------------------------------"
         # Define the migration phase label key
-        export MIGRATION_PHASE_LABEL="canary.tiendanube.com/migration-phase"
+        MIGRATION_PHASE_LABEL="canary.tiendanube.com/migration-phase"
         # Render Helm chart to a temporary file
         helmv3 template \
           << parameters.release-name >> \
@@ -57,12 +54,12 @@ steps:
         # Define the yq expression for extracting the migration phase label
         YQ_EXPR='select(.kind == "Rollout") | .metadata.labels["'"$MIGRATION_PHASE_LABEL"'"]'
         # Extract the migration phase label (empty string if not found)
-        MIGRATION_PHASE=$(yq "$YQ_EXPR" $MIGRATION_PHASE_RAW_FILE)
+        export MIGRATION_PHASE=$(yq "$YQ_EXPR" $MIGRATION_PHASE_RAW_FILE)
         # Default to "completed" if not found or is 'null'
         if [[ -n "$MIGRATION_PHASE" ]] && [[ "$MIGRATION_PHASE" != "null" ]]; then
           case "$MIGRATION_PHASE" in
             safe|initial|traffic|completed)
-              echo "$MIGRATION_PHASE" > << parameters.output-file-name >>
+              echo "✅ Valid migration phase: $MIGRATION_PHASE"
               ;;
             *)
               echo "❌ Error: MIGRATION_PHASE must be one of: safe, initial, traffic, completed"
@@ -71,8 +68,15 @@ steps:
               ;;
           esac
         else
-          echo "completed" > << parameters.output-file-name >>
+          MIGRATION_PHASE="completed"
+          echo "ℹ️  No migration phase found. Defaulting to: $MIGRATION_PHASE"
+        fi
+        if ! yq -i '.canaryMigrationPhaseOverride = strenv(MIGRATION_PHASE)' << parameters.profile-file-name >>; then
+          echo "❌ Error: Failed to write migration phase to << parameters.profile-file-name >>"
+          exit 1
         fi
         echo "------------------------------------------------------"
-        echo "🏷️  Migration phase: $(cat << parameters.output-file-name >>)"
+        echo "🏷️  Migration phase: $MIGRATION_PHASE"
+        echo "🏷️  Environment profile content:"
+        cat << parameters.profile-file-name >>
         echo "------------------------------------------------------"
