[BAC-353] Improve argo rollout status (#23)
* Improve README with useful cli commands

* Improve commands output

Adjust exit message
Improve readability with emojis

* Set default resource_class medium

* Improve parameters handling

Support Helm parameters with whitespaces.
Add case for testing

* Enhance helm-argo-deploy parameters

Add 'helm-app-status-timeout' parameter to specify the duration for watching Argo Application deployments. Update 'rollout-status-timeout' description for clarity and change its default value to '0' to disable the timeout by default. Adjust workflow steps to utilize the new timeout parameter.

* Refactor helm-argo-deploy job to streamline Helm parameters handling. Removed unnecessary environment variable export steps and directly passed parameters to the Python script for improved clarity and efficiency.

* Use files for input/output args

* Improve regex to handle values with spaces

* Add debug info

* Fixed regex to handle values with spaces and hyphens

* Set param as string

* Escape dots

* Quote conflicting string

* Handle escaped chars in echo

Update DD_TAGS environment variable format and adjust echo command for parameter export

* improve python script that parse arguments

* Propagate timeout exit code

Add exit handling for timeout in rollout status checks

* Remove testing bash in args

Remove examples of usages taken from services. that has inline bash expressions in the command args parameter

* Use public chart bucket folder

* Remove boolean arg

---------

Co-authored-by: churru <martin.churruca@tiendanube.com>

diff --git a/src/commands/argo-rollout-status.yml b/src/commands/argo-rollout-status.yml
--- a/src/commands/argo-rollout-status.yml
+++ b/src/commands/argo-rollout-status.yml
@@ -25,25 +25,25 @@ steps:
             i=1
             while true; do
               echo "========================================================"
-              echo "Checking release status (attempt $i)..."
+              echo "🔍 Checking release status (attempt $i)..."
               output=$(kubectl argo rollouts get rollout << parameters.release-name >> \
                 --namespace << parameters.namespace >>)
               echo "$output"
               status=$(echo "$output" | grep "^Status:" | awk '"'"'{print $3}'"'"')
               case "$status" in
                 Healthy|Completed)
-                  echo "Rollout is $status."
+                  echo "✅ Rollout is $status."
                   exit 0
                   ;;
                 Degraded|Error|Aborted)
-                  echo "Release status is $status. Exiting with failure."
+                  echo "❌ Release status is $status. Exiting with failure."
                   exit 1
                   ;;
                 Progressing|Paused)
-                  echo "Release status is $status. Waiting..."
+                  echo "⏳ Release status is $status. Waiting..."
                   ;;
                 *)
-                  echo "Unknown status: $status. Waiting..."
+                  echo "❓ Unknown status: $status. Waiting..."
                   ;;
               esac
               i=$((i+1))
@@ -51,7 +51,9 @@ steps:
             done
           '
           TIMEOUT_RESULT=$?
-          if [ $TIMEOUT_RESULT -eq 124 ]; then
-            echo "Timeout reached while checking release status. Exiting with failure."
+          if [[ $TIMEOUT_RESULT -eq 124 ]]; then
+            echo "⏰ Timeout reached while checking release status."
             exit 0
+          else
+            exit $TIMEOUT_RESULT
           fi
diff --git a/src/commands/helm-status.yml b/src/commands/helm-status.yml
--- a/src/commands/helm-status.yml
+++ b/src/commands/helm-status.yml
@@ -33,7 +33,7 @@ steps:
             i=1
             while true; do
               echo "========================================================"
-              echo "Checking release status (attempt $i)..."
+              echo "🔍 Checking release status (attempt $i)..."
               output=$(helmv3 status << parameters.release-name >> --namespace << parameters.namespace >> \
                 <<# parameters.show-description >>--show-desc<</parameters.show-description>> \
                 <<# parameters.show-resources >>--show-resources<</parameters.show-resources>>)
@@ -41,18 +41,18 @@ steps:
               status=$(echo "$output" | grep "^STATUS:" | awk '"'"'{print $2}'"'"')
               case "$status" in
                 deployed)
-                  echo "Release is deployed."
+                  echo "✅ Release is deployed."
                   exit 0
                   ;;
                 failed|superseded|uninstalled)
-                  echo "Release status is $status. Exiting with failure."
+                  echo "❌ Release status is $status. Exiting with failure."
                   exit 1
                   ;;
                 pending-install|pending-upgrade|pending-rollback)
-                  echo "Release status is $status. Waiting..."
+                  echo "⏳ Release status is $status. Waiting..."
                   ;;
                 *)
-                  echo "Unknown status: $status. Waiting..."
+                  echo "❓ Unknown status: $status. Waiting..."
                   ;;
               esac
               i=$((i+1))
@@ -60,7 +60,9 @@ steps:
             done
           '
           TIMEOUT_RESULT=$?
-          if [ $TIMEOUT_RESULT -eq 124 ]; then
-            echo "Timeout reached while checking release status. Exiting with failure."
+          if [[ $TIMEOUT_RESULT -eq 124 ]]; then
+            echo "⏰ Timeout reached while checking release status."
             exit 0
+          else
+            exit $TIMEOUT_RESULT
           fi
